# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster_aggregation', '0010_valuecountresult_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationLayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AggregationLayerZoomRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_zoom', models.IntegerField()),
                ('max_zoom', models.IntegerField()),
                ('aggregationlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationLayer')),
                ('aggregationlayergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster_aggregation.AggregationLayerGroup')),
            ],
        ),
        migrations.AddField(
            model_name='aggregationlayergroup',
            name='aggregationlayers',
            field=models.ManyToManyField(through='raster_aggregation.AggregationLayerZoomRange', to='raster_aggregation.AggregationLayer'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregationlayerzoomrange',
            unique_together=set([('aggregationlayergroup', 'aggregationlayer')]),
        ),
    ]
